###
POST http://localhost:8080/login
Content-Type: application/json

{
  "id": "user",
  "password": "12345",
  "email": "abcd1234@naver.com",
  "state": "sleep"
}

###
POST http://localhost:8080/login?id=user&password=12345
Content-Type: application/x-www-form-urlencoded