###
POST http://localhost:8081/login
Content-Type: application/json
X-USER-ID: 1

{
  "id": "user1",
  "password": "1111"
}

###
PUT http://localhost:8081/accounts/user2/state
Content-Type: application/json

{
  "state": "inactive"
}

###
POST http://localhost:8081/login
Content-Type: application/json

{
  "id": "user",
  "password": "1111"
}



###
POST http://localhost:8080/login?id=user&password=12345
Content-Type: application/x-www-form-urlencoded